# For syntax, see https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# This workflow is triggered manually on the "Actions" tab on GitHub, and can be used to create releases.

name: Make and publish a GDExtension build for all supported platforms
on:
  workflow_dispatch:
    inputs:
      release:
        description: "Create a new GitHub release (Required to publish on Asset Lib)."
        type: boolean
        required: false
        default: false
      tag_name:
        description: "Tag name"
        required: false
        default: ""
      release_name:
        description: "Release name"
        required: false
        default: ""
      publish:
        description: "Publish new version to asset lib (Requires ASSET_STORE_USERNAME and ASSET_STORE_PASSWORD secrets, and .asset-template.json.hb to be edited)."
        type: boolean
        required: false
        default: false
      asset_id:
        description: "The asset ID"
        required: false
        default: "4372"


permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # A build is made for every possible combination of parameters
        # You can add or remove entries from the arrays of each parameter to customize which builds you want to run.
        # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
        target:
          [
            { platform: linux, arch: x86_64, os: ubuntu-22.04 },
            { platform: linux, arch: x86_32, os: ubuntu-22.04 },
            { platform: linux, arch: arm64, os: ubuntu-22.04-arm },
            { platform: linux, arch: arm32, os: ubuntu-22.04-arm },
            { platform: windows, arch: x86_64, os: windows-latest },
            { platform: windows, arch: x86_32, os: windows-latest },
            { platform: windows, arch: arm64, os: windows-latest },
            { platform: macos, arch: universal, os: macos-latest },
            { platform: android, arch: x86_64, os: ubuntu-22.04 },
            { platform: android, arch: x86_32, os: ubuntu-22.04 },
            { platform: android, arch: arm64, os: ubuntu-22.04 },
            { platform: android, arch: arm32, os: ubuntu-22.04 },
            { platform: ios, arch: arm64, os: macos-latest },
            { platform: web, arch: wasm32, os: ubuntu-22.04 },
          ]
        target-type: [template_debug, template_release]
        float-precision: [single]

    runs-on: ${{ matrix.target.os }}
    steps:
      # Clone this repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Add linux x86_32 toolchain
      - name: Install multilib support
        if: ${{ matrix.target.platform == 'linux' && matrix.target.arch == 'x86_32' }}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib

      # Setup dependencies
      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      # Build GDExtension (with caches)

      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Build GDExtension Debug Build
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} precision=${{ matrix.float-precision }}

      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      # Clean up compilation files
      - name: Windows - Delete compilation files
        if: ${{ matrix.target.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

      # Upload the build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: interactive-grid-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/demo/bin/**

  # Merges all the build artifacts together into a single interactive-grid artifact.
  # If you comment out this step, all the builds will be uploaded individually.
  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: interactive-grid
          pattern: interactive-grid-*
          delete-merged: true
  
  # Create a GitHub release
  release:
    if: ${{ inputs.release}}
    runs-on: ubuntu-22.04
    needs: merge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download merged artifact
        uses: actions/download-artifact@v4
        with:
          name: interactive-grid
          path: release/addons/interactive-grid

      - name: Create archive
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          cd release && zip -r ../interactive-grid.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body_path: CHANGELOG.md
          make_latest: true
          files: interactive-grid.zip

  publish:
    if: ${{ inputs.publish && inputs.release }}
    runs-on: ubuntu-22.04
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Publish new version to asset lib
        uses: deep-entertainment/godot-asset-lib-action@v0.4.0
        with:
          # https://docs.github.com/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets
          username: ${{ secrets.ASSET_STORE_USERNAME }}
          password: ${{ secrets.ASSET_STORE_PASSWORD }}
          assetId: ${{ github.event.inputs.asset_id }}